host                = 0.0.0.0
port                = 34001
templates           = /opt/gscserver/share
access_log          = /opt/gscserver/var/access_log
error_log           = /opt/gscserver/var/error_log
table_timeout       = 5000
gettbl_log_interval = 2
chat_server         = 127.0.0.1
show_started_rooms  = 1
proxy_key           = coswasmproxy
udp_host            = __UDP_HOST__
udp_port            = 8792
udp_interval        = 2000
udp_transport       = udp
