#!/usr/bin/env python3
# cos_gen_marshalers.py — generate game_api marshalers from the engine signatures.
# Each game_api fn: DLL passes cdecl args on the guest stack; the marshaler
# translates pointer args (guest addr -> gp()) and value args (direct), calls the
# real engine C++ function, returns the result into EAX. Emits cos_gameapi_gen.cpp.
import re, sys, glob

# Source of truth = the ENGINE's actual definitions (extern "C" __declspec(dllexport)),
# NOT Ildar's game_api.h (which has wrong return types / arg counts, e.g. AI_Torg int
# vs void, ChangeUnitParam 4 vs 5 args -> WASM signature_mismatch traps).
ENGINE_SRC = r"C:\cossacks_wasm\src\MainExe"
OUT = r"C:\cossacks_wasm\x86\cos_gameapi_gen.cpp"

# extern "C" __declspec( dllexport ) RET NAME( args ) {   (handles `dllexport )RET` no-space + multiline args)
DEF_RE = re.compile(r'extern\s+"C"\s+__declspec\(\s*dllexport\s*\)\s*([\w\*]+(?:\s*\*)?)\s+(\w+)\s*\(([^)]*)\)\s*\{', re.S)

seen = {}
for f in glob.glob(ENGINE_SRC + r"\*.cpp"):
    s = open(f, encoding='latin-1', errors='ignore').read()
    for m in DEF_RE.finditer(s):
        ret, name, args = m.group(1).strip(), m.group(2), m.group(3).strip()
        if name in seen: continue
        seen[name] = (ret, args)

funcs = []
for name, (ret, args) in seen.items():
    if '...' in args:
        funcs.append((ret, name, None)); continue
    if args in ('', 'void'):
        funcs.append((ret, name, [])); continue
    parts = [a.strip() for a in args.split(',')]
    argl = []
    for p in parts:
        mm = re.match(r'(.*?)(\w+)$', p)   # split TYPE NAME (name optional)
        typ = mm.group(1).strip() if mm else p
        if not typ: typ = p
        argl.append(typ)
    funcs.append((ret, name, argl))
print("parsed %d engine dllexport game_api functions" % len(funcs))

out = ['// AUTO-GENERATED by cos_gen_marshalers.py — game_api -> engine bridge.',
       '// Compiled WITH the engine (real function definitions + types).',
       'extern "C" {', '#include "cpu.h"', '}', '#include "cos_x86.h"', '',
       '// Engine game_api types (from the engine headers at integration time).',
       'struct GAMEOBJ; struct OneUnit; struct UnitExCaps;',
       'typedef unsigned char byte; typedef unsigned short word;',
       'typedef int BOOL; typedef unsigned long DWORD; typedef long HRESULT; typedef unsigned int UINT;', '',
       '// The real engine functions (declared here; defined in the engine TUs).']

# forward-declare engine functions — extern "C" (engine defines them as
# extern "C" __declspec(dllexport)) so plain-name linkage matches.
out.append('extern "C" {')
for ret, name, argl in funcs:
    if argl is None:
        out.append('  %s %s(char*, ...);' % (ret, name)); continue
    sig = ', '.join(argl) if argl else 'void'
    out.append('  %s %s(%s);' % (ret, name, sig))
out.append('}')

out.append('')
out.append('// marshalers')
def is_ptr(t): return t.endswith('*')
for ret, name, argl in funcs:
    if argl is None:  # variadic: pass fmt only (best-effort)
        if ret == 'void':
            out.append('static uint32_t m_%s(const uint32_t* a){ %s((char*)gp(a[0])); return 0; }' % (name, name))
        else:
            out.append('static uint32_t m_%s(const uint32_t* a){ return (uint32_t)%s((char*)gp(a[0])); }' % (name, name))
        continue
    call_args = []
    for i, t in enumerate(argl):
        if is_ptr(t): call_args.append('(%s)gp(a[%d])' % (t, i))
        else:         call_args.append('(%s)a[%d]' % (t, i))
    call = '%s(%s)' % (name, ', '.join(call_args))
    if ret == 'void':
        body = '%s; return 0;' % call
    else:
        body = 'return (uint32_t)%s;' % call
    out.append('static uint32_t m_%s(const uint32_t* a){ (void)a; %s }' % (name, body))

out.append('')
out.append('extern "C" void cos_register_gameapi(void){')
for ret, name, argl in funcs:
    ac = 1 if argl is None else len(argl)
    out.append('  cos_api_register("%s", %d, m_%s);' % (name, ac, name))
out.append('}')

open(OUT, 'w').write('\n'.join(out) + '\n')
print("generated %d marshalers -> %s" % (len(funcs), OUT))
