// AUTO-GENERATED by cos_gen_marshalers.py � game_api -> engine bridge.
// Compiled WITH the engine (real function definitions + types).
extern "C" {
#include "cpu.h"
}
#include "cos_x86.h"
#include <string.h>
#include <stdint.h>

// Engine game_api types (from the engine headers at integration time).
struct GAMEOBJ; struct OneUnit; struct UnitExCaps;
typedef unsigned char byte; typedef unsigned short word;
typedef int BOOL; typedef unsigned long DWORD; typedef long HRESULT; typedef unsigned int UINT;

// The real engine functions (declared here; defined in the engine TUs).
extern "C" {
  void AssignNation(byte, byte);
  bool RegisterUnits(GAMEOBJ*, char*);
  bool RegisterUnitsForm(GAMEOBJ*, char*);
  bool RegisterString(GAMEOBJ*, char*);
  bool RegisterSound(GAMEOBJ*, char*);
  void RegisterVar(void*, int);
  void RegisterZone(GAMEOBJ*, char*);
  void RegisterVisibleZone(GAMEOBJ*, char*);
  bool RegisterUnitType(GAMEOBJ*, char*);
  bool RegisterUpgrade(GAMEOBJ*, char*);
  bool SafeRegisterUpgrade(GAMEOBJ*, char*);
  void InitialUpgrade(char*, char*);
  void DisableUpgrade(byte, GAMEOBJ*);
  void EnableUpgrade(byte, GAMEOBJ*);
  void EnableUnit(byte, GAMEOBJ*, bool);
  bool RegisterFormation(GAMEOBJ*, char*);
  int GetUnitsAmount0(GAMEOBJ*, byte);
  void ShowAlarm(GAMEOBJ*);
  void SelectUnitsInZone(GAMEOBJ*, byte, bool);
  void ChangeUnitParam(GAMEOBJ*, byte, int, int, int);
  void SelectTypeOfUnitsInZone(GAMEOBJ*, GAMEOBJ*, byte, bool);
  int GetUnitsAmount1(GAMEOBJ*, GAMEOBJ*);
  int GetUnitsAmount2(GAMEOBJ*, GAMEOBJ*, byte);
  int GetTotalAmount0(GAMEOBJ*);
  int GetTotalAmount1(GAMEOBJ*, byte);
  int GetTotalAmount2(GAMEOBJ*, GAMEOBJ*, byte);
  int GetReadyAmount(GAMEOBJ*, byte);
  int GetAmountOfWarriors(byte);
  bool IsUpgradeDoing(GAMEOBJ*, byte);
  bool IsUpgradeDone(GAMEOBJ*, byte);
  bool IsUpgradeEnabled(GAMEOBJ*, byte);
  int GetDied(GAMEOBJ*, byte);
  bool CreateObject0(GAMEOBJ*, GAMEOBJ*, GAMEOBJ*, byte, GAMEOBJ*, byte);
  void ClearSelection(byte);
  void SelectUnits(GAMEOBJ*, bool);
  void SelectUnits1(byte, GAMEOBJ*, bool);
  void SelectUnitsType(GAMEOBJ*, byte, bool);
  bool SelDie(byte);
  void DoMessagesBrief(void);
  void SelErase(byte);
  void SelAttackGroup(byte, GAMEOBJ*);
  bool SelOpenGates(byte);
  int GetNInside(byte);
  int GetMaxInside(byte);
  void PushUnitAway(byte);
  void PushAllUnitsAway(byte);
  void SendUnitsToTransport(byte);
  bool CheckLeaveAbility(byte);
  void AttackZoneByArtillery(GAMEOBJ*, GAMEOBJ*, byte);
  void AttackBuildingsInZone(GAMEOBJ*, GAMEOBJ*, byte);
  void ProduceOneUnit(byte, GAMEOBJ*);
  bool SelCloseGates(byte);
  bool SelSendTo(byte, GAMEOBJ*, byte, byte);
  bool SelSendAndKill(byte, GAMEOBJ*, byte, byte);
  bool Patrol(byte, GAMEOBJ*, byte);
  void ChangeFriends(byte, byte);
  void SelChangeNation(byte, byte);
  void SelAutoKill(byte);
  void SetStandGround(byte, byte);
  void AllowAttack(byte, byte);
  void HINT(GAMEOBJ*, int);
  void DisableMission(char);
  void EnableMission(char);
  void SetVictoryText(char*);
  void SetLooseText(char*);
  void ShowVictory(void);
  void LooseGame(void);
  void ShowCentralText(char*, int);
  void ShowPage(char*);
  void ShowPageParam(char*, ...);
  const char* cos_scen_page_fmt(const char*);   // returns a scenario page's format string by name
  bool AskQuestion(char*);
  int AskComplexQuestion(int, char*, byte, char*, byte, char*);
  int GetResource(byte, byte);
  void AddResource(byte, byte, int);
  void SetResource(byte, byte, int);
  int GetUnitCost(byte, GAMEOBJ*, byte);
  int GetUpgradeCost(byte, GAMEOBJ*, byte);
  byte Trigg(byte);
  void SetTrigg(byte, byte);
  word WTrigg(byte);
  void SetWTrigg(byte, word);
  void RunAI(byte);
  void RunAIWithPeasants(byte, char*);
  void RunTimer(byte, int);
  bool TimerDone(byte);
  bool TimerDoneFirst(byte);
  bool TimerIsEmpty(byte);
  void FreeTimer(byte);
  int GetTime(byte);
  int GetGlobalTime(void);
  bool UnitsCenter(GAMEOBJ*, GAMEOBJ*, word);
  void RefreshScreen(void);
  bool SelCenter(GAMEOBJ*, byte, int);
  bool CreateZoneNearUnit(GAMEOBJ*, GAMEOBJ*, GAMEOBJ*, byte, int);
  bool CreateZoneNearGroup(GAMEOBJ*, GAMEOBJ*, GAMEOBJ*, int);
  void SetLightSpot(GAMEOBJ*, int, byte);
  void ClearLightSpot(byte);
  void SetStartPoint(GAMEOBJ*);
  void AttackEnemyInZone(GAMEOBJ*, GAMEOBJ*, byte);
  int GetMyNation(void);
  int GetTopDst(GAMEOBJ*, GAMEOBJ*);
  void StartAI(byte, char*, int, int, int, int);
  void DoNotUseSelInAI(byte);
  void SetTutorial(bool);
  bool GetQuestPressed(void);
  void SetAIProperty(byte, int, int);
  int AskMultilineQuestion(int, char*, byte, char*);
  void SetReadyState(GAMEOBJ*, bool);
  void TakeFood(GAMEOBJ*);
  void TakeWood(GAMEOBJ*);
  void TakeStone(GAMEOBJ*);
  void RepairBuildingsBySel(byte, GAMEOBJ*);
  bool CheckBuildingsComplete(GAMEOBJ*);
  int GetKilled(GAMEOBJ*);
  int GetUnitsByNation(GAMEOBJ*, byte);
  void ProduceUnit(GAMEOBJ*, GAMEOBJ*, GAMEOBJ*);
  void ProduceUnitFast(GAMEOBJ*, GAMEOBJ*, GAMEOBJ*, int);
  void SaveSelectedUnits(byte, GAMEOBJ*, bool);
  bool CheckProduction(GAMEOBJ*);
  bool CreateBuilding(byte, GAMEOBJ*, GAMEOBJ*, GAMEOBJ*);
  void SetDestPoint(GAMEOBJ*, GAMEOBJ*);
  void RegisterDynGroup(GAMEOBJ*);
  int GetNUnits(GAMEOBJ*);
  bool GetUnitInfo(GAMEOBJ*, int, OneUnit*);
  void SetUnitInfo(OneUnit*);
  void RemoveGroup(GAMEOBJ*, GAMEOBJ*);
  int GetAINation(void);
  bool TryUnit(GAMEOBJ*, int, byte, byte);
  bool TryUpgrade(GAMEOBJ*, int, int);
  void SetMineBalanse(int, word*);
  void SetPDistribution(int, int, int);
  void AssignAmountOfMineUpgrades(int);
  bool AssignMineUpgrade(word, char*, word);
  void AssignMine(char*);
  void AssignPeasant(char*);
  void AssignHouse(char*);
  void AssignWall(char*);
  void SET_MINE_CAPTURE_RADIUS(int);
  void SET_MINE_UPGRADE1_RADIUS(int);
  void SET_MINE_UPGRADE2_RADIUS(int);
  void SET_DEFAULT_MAX_WORKERS(int);
  void SET_MIN_PEASANT_BRIGADE(int);
  int GetMoney(byte);
  int GetUnits(GAMEOBJ*);
  int GetUnitsByUsage(byte, byte);
  void AI_Torg(byte, byte, int);
  int GetTorgResult(byte, byte, int);
  int GetReadyUnits(GAMEOBJ*);
  void SetUpgradeLock(byte, byte);
  void SetDefSettings(int, int);
  int GetMaxPeasantsInMines(void);
  bool UpgIsDone(GAMEOBJ*);
  bool UpgIsRun(GAMEOBJ*);
  void SetMinesBuildingRules(int*, int);
  void SetMinesUpgradeRules(int*);
  bool FieldExist(void);
  int GetDifficulty(void);
  int GetStartRes(void);
  int GetDiff(byte);
  int GetResOnMap(void);
  int GetLandType(void);
  void SetStandartVictory(void);
  bool NationIsErased(byte);
  void AssignFormUnit(char*);
  void SetPlayerName(byte, char*);
  int GetMaxPeaceTime(void);
  int GetPeaceTimeLeft(void);
  int GetRandomIndex(void);
  void SetAIRegister(int, int);
  int GetAIRegister(int);
  int GetExtraction(byte);
  void SetDefenseState(byte);
  void MissErrorMessage(char*, char*);
  void RunMapeditor(char*);
  void RunUserMission(char*);
  bool GetUnitExCaps(int, UnitExCaps*, bool);
  int InsertUnitToGroup(GAMEOBJ*, GAMEOBJ*, int);
  void RemoveUnitFromGroup(GAMEOBJ*, int);
  bool GetZoneCoor(GAMEOBJ*, int*, int*);
  void PastePiece(GAMEOBJ*, char*);
  void SelectBuildingsInZone(byte, GAMEOBJ*, GAMEOBJ*, bool);
}

// marshalers
static uint32_t m_AssignNation(const uint32_t* a){ (void)a; AssignNation((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_RegisterUnits(const uint32_t* a){ (void)a; return (uint32_t)RegisterUnits((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_RegisterUnitsForm(const uint32_t* a){ (void)a; return (uint32_t)RegisterUnitsForm((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_RegisterString(const uint32_t* a){ (void)a; return (uint32_t)RegisterString((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_RegisterSound(const uint32_t* a){ (void)a; return (uint32_t)RegisterSound((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_RegisterVar(const uint32_t* a){ (void)a; RegisterVar((void*)gp(a[0]), (int)a[1]); return 0; }
static uint32_t m_RegisterZone(const uint32_t* a){ (void)a; RegisterZone((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); return 0; }
static uint32_t m_RegisterVisibleZone(const uint32_t* a){ (void)a; RegisterVisibleZone((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); return 0; }
static uint32_t m_RegisterUnitType(const uint32_t* a){ (void)a; return (uint32_t)RegisterUnitType((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_RegisterUpgrade(const uint32_t* a){ (void)a; return (uint32_t)RegisterUpgrade((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_SafeRegisterUpgrade(const uint32_t* a){ (void)a; return (uint32_t)SafeRegisterUpgrade((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_InitialUpgrade(const uint32_t* a){ (void)a; InitialUpgrade((char*)gp(a[0]), (char*)gp(a[1])); return 0; }
static uint32_t m_DisableUpgrade(const uint32_t* a){ (void)a; DisableUpgrade((byte)a[0], (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_EnableUpgrade(const uint32_t* a){ (void)a; EnableUpgrade((byte)a[0], (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_EnableUnit(const uint32_t* a){ (void)a; EnableUnit((byte)a[0], (GAMEOBJ*)gp(a[1]), (bool)a[2]); return 0; }
static uint32_t m_RegisterFormation(const uint32_t* a){ (void)a; return (uint32_t)RegisterFormation((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); }
static uint32_t m_GetUnitsAmount0(const uint32_t* a){ (void)a; return (uint32_t)GetUnitsAmount0((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_ShowAlarm(const uint32_t* a){ (void)a; ShowAlarm((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_SelectUnitsInZone(const uint32_t* a){ (void)a; SelectUnitsInZone((GAMEOBJ*)gp(a[0]), (byte)a[1], (bool)a[2]); return 0; }
static uint32_t m_ChangeUnitParam(const uint32_t* a){ (void)a; ChangeUnitParam((GAMEOBJ*)gp(a[0]), (byte)a[1], (int)a[2], (int)a[3], (int)a[4]); return 0; }
static uint32_t m_SelectTypeOfUnitsInZone(const uint32_t* a){ (void)a; SelectTypeOfUnitsInZone((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2], (bool)a[3]); return 0; }
static uint32_t m_GetUnitsAmount1(const uint32_t* a){ (void)a; return (uint32_t)GetUnitsAmount1((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1])); }
static uint32_t m_GetUnitsAmount2(const uint32_t* a){ (void)a; return (uint32_t)GetUnitsAmount2((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2]); }
static uint32_t m_GetTotalAmount0(const uint32_t* a){ (void)a; return (uint32_t)GetTotalAmount0((GAMEOBJ*)gp(a[0])); }
static uint32_t m_GetTotalAmount1(const uint32_t* a){ (void)a; return (uint32_t)GetTotalAmount1((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_GetTotalAmount2(const uint32_t* a){ (void)a; return (uint32_t)GetTotalAmount2((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2]); }
static uint32_t m_GetReadyAmount(const uint32_t* a){ (void)a; return (uint32_t)GetReadyAmount((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_GetAmountOfWarriors(const uint32_t* a){ (void)a; return (uint32_t)GetAmountOfWarriors((byte)a[0]); }
static uint32_t m_IsUpgradeDoing(const uint32_t* a){ (void)a; return (uint32_t)IsUpgradeDoing((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_IsUpgradeDone(const uint32_t* a){ (void)a; return (uint32_t)IsUpgradeDone((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_IsUpgradeEnabled(const uint32_t* a){ (void)a; return (uint32_t)IsUpgradeEnabled((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_GetDied(const uint32_t* a){ (void)a; return (uint32_t)GetDied((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_CreateObject0(const uint32_t* a){ (void)a; return (uint32_t)CreateObject0((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (byte)a[3], (GAMEOBJ*)gp(a[4]), (byte)a[5]); }
static uint32_t m_ClearSelection(const uint32_t* a){ (void)a; ClearSelection((byte)a[0]); return 0; }
static uint32_t m_SelectUnits(const uint32_t* a){ (void)a; SelectUnits((GAMEOBJ*)gp(a[0]), (bool)a[1]); return 0; }
static uint32_t m_SelectUnits1(const uint32_t* a){ (void)a; SelectUnits1((byte)a[0], (GAMEOBJ*)gp(a[1]), (bool)a[2]); return 0; }
static uint32_t m_SelectUnitsType(const uint32_t* a){ (void)a; SelectUnitsType((GAMEOBJ*)gp(a[0]), (byte)a[1], (bool)a[2]); return 0; }
static uint32_t m_SelDie(const uint32_t* a){ (void)a; return (uint32_t)SelDie((byte)a[0]); }
static uint32_t m_DoMessagesBrief(const uint32_t* a){ (void)a; DoMessagesBrief(); return 0; }
static uint32_t m_SelErase(const uint32_t* a){ (void)a; SelErase((byte)a[0]); return 0; }
static uint32_t m_SelAttackGroup(const uint32_t* a){ (void)a; SelAttackGroup((byte)a[0], (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_SelOpenGates(const uint32_t* a){ (void)a; return (uint32_t)SelOpenGates((byte)a[0]); }
static uint32_t m_GetNInside(const uint32_t* a){ (void)a; return (uint32_t)GetNInside((byte)a[0]); }
static uint32_t m_GetMaxInside(const uint32_t* a){ (void)a; return (uint32_t)GetMaxInside((byte)a[0]); }
static uint32_t m_PushUnitAway(const uint32_t* a){ (void)a; PushUnitAway((byte)a[0]); return 0; }
static uint32_t m_PushAllUnitsAway(const uint32_t* a){ (void)a; PushAllUnitsAway((byte)a[0]); return 0; }
static uint32_t m_SendUnitsToTransport(const uint32_t* a){ (void)a; SendUnitsToTransport((byte)a[0]); return 0; }
static uint32_t m_CheckLeaveAbility(const uint32_t* a){ (void)a; return (uint32_t)CheckLeaveAbility((byte)a[0]); }
static uint32_t m_AttackZoneByArtillery(const uint32_t* a){ (void)a; AttackZoneByArtillery((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2]); return 0; }
static uint32_t m_AttackBuildingsInZone(const uint32_t* a){ (void)a; AttackBuildingsInZone((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2]); return 0; }
static uint32_t m_ProduceOneUnit(const uint32_t* a){ (void)a; ProduceOneUnit((byte)a[0], (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_SelCloseGates(const uint32_t* a){ (void)a; return (uint32_t)SelCloseGates((byte)a[0]); }
static uint32_t m_SelSendTo(const uint32_t* a){ (void)a; return (uint32_t)SelSendTo((byte)a[0], (GAMEOBJ*)gp(a[1]), (byte)a[2], (byte)a[3]); }
static uint32_t m_SelSendAndKill(const uint32_t* a){ (void)a; return (uint32_t)SelSendAndKill((byte)a[0], (GAMEOBJ*)gp(a[1]), (byte)a[2], (byte)a[3]); }
static uint32_t m_Patrol(const uint32_t* a){ (void)a; return (uint32_t)Patrol((byte)a[0], (GAMEOBJ*)gp(a[1]), (byte)a[2]); }
static uint32_t m_ChangeFriends(const uint32_t* a){ (void)a; ChangeFriends((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_SelChangeNation(const uint32_t* a){ (void)a; SelChangeNation((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_SelAutoKill(const uint32_t* a){ (void)a; SelAutoKill((byte)a[0]); return 0; }
static uint32_t m_SetStandGround(const uint32_t* a){ (void)a; SetStandGround((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_AllowAttack(const uint32_t* a){ (void)a; AllowAttack((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_HINT(const uint32_t* a){ (void)a; HINT((GAMEOBJ*)gp(a[0]), (int)a[1]); return 0; }
static uint32_t m_DisableMission(const uint32_t* a){ (void)a; DisableMission((char)a[0]); return 0; }
static uint32_t m_EnableMission(const uint32_t* a){ (void)a; EnableMission((char)a[0]); return 0; }
static uint32_t m_SetVictoryText(const uint32_t* a){ (void)a; SetVictoryText((char*)gp(a[0])); return 0; }
static uint32_t m_SetLooseText(const uint32_t* a){ (void)a; SetLooseText((char*)gp(a[0])); return 0; }
static uint32_t m_ShowVictory(const uint32_t* a){ (void)a; ShowVictory(); return 0; }
static uint32_t m_LooseGame(const uint32_t* a){ (void)a; LooseGame(); return 0; }
static uint32_t m_ShowCentralText(const uint32_t* a){ (void)a; ShowCentralText((char*)gp(a[0]), (int)a[1]); return 0; }
static uint32_t m_ShowPage(const uint32_t* a){ (void)a; ShowPage((char*)gp(a[0])); return 0; }
// MANUAL FIX (mirror in cos_gen_marshalers.py if ever regenerating): ShowPageParam is variadic —
// the scenario page's format string (e.g. "Прошло %d минут!") consumes the extra args inside the
// engine's vsprintf. The generator forwarded ONLY the page-name arg, so the varargs were never
// passed and vsprintf read native-stack garbage — the constant "Прошло 1668509029 минут!" bug
// (0x63736D65 = leftover stack bytes). Fix: gather the guest's varargs (argc bumped to 16 at
// registration so sh_gameapi copies them off the guest stack), translate %s pointers guest->host,
// and forward the values to the real variadic ShowPageParam. vsprintf then uses only as many as the
// format needs; extra forwarded slots are ignored.
static uint32_t m_ShowPageParam(const uint32_t* a){
  char* name = (char*)gp(a[0]);
  const char* fmt = cos_scen_page_fmt(name);
  uint32_t A[16] = {0};
  if (fmt) {
    int k = 0;
    for (const char* p = fmt; *p && k < 15; ++p) {
      if (*p != '%') continue;
      ++p;
      if (*p == '%') continue;                                   // literal %%
      while (*p && strchr("-+ #0.123456789*hlLqjzt", *p)) ++p;    // flags / width / precision / length
      char c = *p;
      uint32_t g = a[1 + k];
      A[k] = (c == 's') ? (uint32_t)(uintptr_t)gp(g) : g;          // %s: guest ptr -> host ptr
      ++k;
    }
  }
  ShowPageParam(name, A[0],A[1],A[2],A[3],A[4],A[5],A[6],A[7],
                      A[8],A[9],A[10],A[11],A[12],A[13],A[14],A[15]);
  return 0;
}
static uint32_t m_AskQuestion(const uint32_t* a){ (void)a; return (uint32_t)AskQuestion((char*)gp(a[0])); }
static uint32_t m_AskComplexQuestion(const uint32_t* a){ (void)a; return (uint32_t)AskComplexQuestion((int)a[0], (char*)gp(a[1]), (byte)a[2], (char*)gp(a[3]), (byte)a[4], (char*)gp(a[5])); }
static uint32_t m_GetResource(const uint32_t* a){ (void)a; return (uint32_t)GetResource((byte)a[0], (byte)a[1]); }
static uint32_t m_AddResource(const uint32_t* a){ (void)a; AddResource((byte)a[0], (byte)a[1], (int)a[2]); return 0; }
static uint32_t m_SetResource(const uint32_t* a){ (void)a; SetResource((byte)a[0], (byte)a[1], (int)a[2]); return 0; }
static uint32_t m_GetUnitCost(const uint32_t* a){ (void)a; return (uint32_t)GetUnitCost((byte)a[0], (GAMEOBJ*)gp(a[1]), (byte)a[2]); }
static uint32_t m_GetUpgradeCost(const uint32_t* a){ (void)a; return (uint32_t)GetUpgradeCost((byte)a[0], (GAMEOBJ*)gp(a[1]), (byte)a[2]); }
static uint32_t m_Trigg(const uint32_t* a){ (void)a; return (uint32_t)Trigg((byte)a[0]); }
static uint32_t m_SetTrigg(const uint32_t* a){ (void)a; SetTrigg((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_WTrigg(const uint32_t* a){ (void)a; return (uint32_t)WTrigg((byte)a[0]); }
static uint32_t m_SetWTrigg(const uint32_t* a){ (void)a; SetWTrigg((byte)a[0], (word)a[1]); return 0; }
static uint32_t m_RunAI(const uint32_t* a){ (void)a; RunAI((byte)a[0]); return 0; }
static uint32_t m_RunAIWithPeasants(const uint32_t* a){ (void)a; RunAIWithPeasants((byte)a[0], (char*)gp(a[1])); return 0; }
static uint32_t m_RunTimer(const uint32_t* a){ (void)a; RunTimer((byte)a[0], (int)a[1]); return 0; }
static uint32_t m_TimerDone(const uint32_t* a){ (void)a; return (uint32_t)TimerDone((byte)a[0]); }
static uint32_t m_TimerDoneFirst(const uint32_t* a){ (void)a; return (uint32_t)TimerDoneFirst((byte)a[0]); }
static uint32_t m_TimerIsEmpty(const uint32_t* a){ (void)a; return (uint32_t)TimerIsEmpty((byte)a[0]); }
static uint32_t m_FreeTimer(const uint32_t* a){ (void)a; FreeTimer((byte)a[0]); return 0; }
static uint32_t m_GetTime(const uint32_t* a){ (void)a; return (uint32_t)GetTime((byte)a[0]); }
static uint32_t m_GetGlobalTime(const uint32_t* a){ (void)a; return (uint32_t)GetGlobalTime(); }
static uint32_t m_UnitsCenter(const uint32_t* a){ (void)a; return (uint32_t)UnitsCenter((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (word)a[2]); }
static uint32_t m_RefreshScreen(const uint32_t* a){ (void)a; RefreshScreen(); return 0; }
static uint32_t m_SelCenter(const uint32_t* a){ (void)a; return (uint32_t)SelCenter((GAMEOBJ*)gp(a[0]), (byte)a[1], (int)a[2]); }
static uint32_t m_CreateZoneNearUnit(const uint32_t* a){ (void)a; return (uint32_t)CreateZoneNearUnit((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (byte)a[3], (int)a[4]); }
static uint32_t m_CreateZoneNearGroup(const uint32_t* a){ (void)a; return (uint32_t)CreateZoneNearGroup((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (int)a[3]); }
static uint32_t m_SetLightSpot(const uint32_t* a){ (void)a; SetLightSpot((GAMEOBJ*)gp(a[0]), (int)a[1], (byte)a[2]); return 0; }
static uint32_t m_ClearLightSpot(const uint32_t* a){ (void)a; ClearLightSpot((byte)a[0]); return 0; }
static uint32_t m_SetStartPoint(const uint32_t* a){ (void)a; SetStartPoint((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_AttackEnemyInZone(const uint32_t* a){ (void)a; AttackEnemyInZone((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (byte)a[2]); return 0; }
static uint32_t m_GetMyNation(const uint32_t* a){ (void)a; return (uint32_t)GetMyNation(); }
static uint32_t m_GetTopDst(const uint32_t* a){ (void)a; return (uint32_t)GetTopDst((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1])); }
static uint32_t m_StartAI(const uint32_t* a){ (void)a; StartAI((byte)a[0], (char*)gp(a[1]), (int)a[2], (int)a[3], (int)a[4], (int)a[5]); return 0; }
static uint32_t m_DoNotUseSelInAI(const uint32_t* a){ (void)a; DoNotUseSelInAI((byte)a[0]); return 0; }
static uint32_t m_SetTutorial(const uint32_t* a){ (void)a; SetTutorial((bool)a[0]); return 0; }
static uint32_t m_GetQuestPressed(const uint32_t* a){ (void)a; return (uint32_t)GetQuestPressed(); }
static uint32_t m_SetAIProperty(const uint32_t* a){ (void)a; SetAIProperty((byte)a[0], (int)a[1], (int)a[2]); return 0; }
static uint32_t m_AskMultilineQuestion(const uint32_t* a){ (void)a; return (uint32_t)AskMultilineQuestion((int)a[0], (char*)gp(a[1]), (byte)a[2], (char*)gp(a[3])); }
static uint32_t m_SetReadyState(const uint32_t* a){ (void)a; SetReadyState((GAMEOBJ*)gp(a[0]), (bool)a[1]); return 0; }
static uint32_t m_TakeFood(const uint32_t* a){ (void)a; TakeFood((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_TakeWood(const uint32_t* a){ (void)a; TakeWood((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_TakeStone(const uint32_t* a){ (void)a; TakeStone((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_RepairBuildingsBySel(const uint32_t* a){ (void)a; RepairBuildingsBySel((byte)a[0], (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_CheckBuildingsComplete(const uint32_t* a){ (void)a; return (uint32_t)CheckBuildingsComplete((GAMEOBJ*)gp(a[0])); }
static uint32_t m_GetKilled(const uint32_t* a){ (void)a; return (uint32_t)GetKilled((GAMEOBJ*)gp(a[0])); }
static uint32_t m_GetUnitsByNation(const uint32_t* a){ (void)a; return (uint32_t)GetUnitsByNation((GAMEOBJ*)gp(a[0]), (byte)a[1]); }
static uint32_t m_ProduceUnit(const uint32_t* a){ (void)a; ProduceUnit((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2])); return 0; }
static uint32_t m_ProduceUnitFast(const uint32_t* a){ (void)a; ProduceUnitFast((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (int)a[3]); return 0; }
static uint32_t m_SaveSelectedUnits(const uint32_t* a){ (void)a; SaveSelectedUnits((byte)a[0], (GAMEOBJ*)gp(a[1]), (bool)a[2]); return 0; }
static uint32_t m_CheckProduction(const uint32_t* a){ (void)a; return (uint32_t)CheckProduction((GAMEOBJ*)gp(a[0])); }
static uint32_t m_CreateBuilding(const uint32_t* a){ (void)a; return (uint32_t)CreateBuilding((byte)a[0], (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (GAMEOBJ*)gp(a[3])); }
static uint32_t m_SetDestPoint(const uint32_t* a){ (void)a; SetDestPoint((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_RegisterDynGroup(const uint32_t* a){ (void)a; RegisterDynGroup((GAMEOBJ*)gp(a[0])); return 0; }
static uint32_t m_GetNUnits(const uint32_t* a){ (void)a; return (uint32_t)GetNUnits((GAMEOBJ*)gp(a[0])); }
static uint32_t m_GetUnitInfo(const uint32_t* a){ (void)a; return (uint32_t)GetUnitInfo((GAMEOBJ*)gp(a[0]), (int)a[1], (OneUnit*)gp(a[2])); }
static uint32_t m_SetUnitInfo(const uint32_t* a){ (void)a; SetUnitInfo((OneUnit*)gp(a[0])); return 0; }
static uint32_t m_RemoveGroup(const uint32_t* a){ (void)a; RemoveGroup((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1])); return 0; }
static uint32_t m_GetAINation(const uint32_t* a){ (void)a; return (uint32_t)GetAINation(); }
static uint32_t m_TryUnit(const uint32_t* a){ (void)a; return (uint32_t)TryUnit((GAMEOBJ*)gp(a[0]), (int)a[1], (byte)a[2], (byte)a[3]); }
static uint32_t m_TryUpgrade(const uint32_t* a){ (void)a; return (uint32_t)TryUpgrade((GAMEOBJ*)gp(a[0]), (int)a[1], (int)a[2]); }
static uint32_t m_SetMineBalanse(const uint32_t* a){ (void)a; SetMineBalanse((int)a[0], (word*)gp(a[1])); return 0; }
static uint32_t m_SetPDistribution(const uint32_t* a){ (void)a; SetPDistribution((int)a[0], (int)a[1], (int)a[2]); return 0; }
static uint32_t m_AssignAmountOfMineUpgrades(const uint32_t* a){ (void)a; AssignAmountOfMineUpgrades((int)a[0]); return 0; }
static uint32_t m_AssignMineUpgrade(const uint32_t* a){ (void)a; return (uint32_t)AssignMineUpgrade((word)a[0], (char*)gp(a[1]), (word)a[2]); }
static uint32_t m_AssignMine(const uint32_t* a){ (void)a; AssignMine((char*)gp(a[0])); return 0; }
static uint32_t m_AssignPeasant(const uint32_t* a){ (void)a; AssignPeasant((char*)gp(a[0])); return 0; }
static uint32_t m_AssignHouse(const uint32_t* a){ (void)a; AssignHouse((char*)gp(a[0])); return 0; }
static uint32_t m_AssignWall(const uint32_t* a){ (void)a; AssignWall((char*)gp(a[0])); return 0; }
static uint32_t m_SET_MINE_CAPTURE_RADIUS(const uint32_t* a){ (void)a; SET_MINE_CAPTURE_RADIUS((int)a[0]); return 0; }
static uint32_t m_SET_MINE_UPGRADE1_RADIUS(const uint32_t* a){ (void)a; SET_MINE_UPGRADE1_RADIUS((int)a[0]); return 0; }
static uint32_t m_SET_MINE_UPGRADE2_RADIUS(const uint32_t* a){ (void)a; SET_MINE_UPGRADE2_RADIUS((int)a[0]); return 0; }
static uint32_t m_SET_DEFAULT_MAX_WORKERS(const uint32_t* a){ (void)a; SET_DEFAULT_MAX_WORKERS((int)a[0]); return 0; }
static uint32_t m_SET_MIN_PEASANT_BRIGADE(const uint32_t* a){ (void)a; SET_MIN_PEASANT_BRIGADE((int)a[0]); return 0; }
static uint32_t m_GetMoney(const uint32_t* a){ (void)a; return (uint32_t)GetMoney((byte)a[0]); }
static uint32_t m_GetUnits(const uint32_t* a){ (void)a; return (uint32_t)GetUnits((GAMEOBJ*)gp(a[0])); }
static uint32_t m_GetUnitsByUsage(const uint32_t* a){ (void)a; return (uint32_t)GetUnitsByUsage((byte)a[0], (byte)a[1]); }
static uint32_t m_AI_Torg(const uint32_t* a){ (void)a; AI_Torg((byte)a[0], (byte)a[1], (int)a[2]); return 0; }
static uint32_t m_GetTorgResult(const uint32_t* a){ (void)a; return (uint32_t)GetTorgResult((byte)a[0], (byte)a[1], (int)a[2]); }
static uint32_t m_GetReadyUnits(const uint32_t* a){ (void)a; return (uint32_t)GetReadyUnits((GAMEOBJ*)gp(a[0])); }
static uint32_t m_SetUpgradeLock(const uint32_t* a){ (void)a; SetUpgradeLock((byte)a[0], (byte)a[1]); return 0; }
static uint32_t m_SetDefSettings(const uint32_t* a){ (void)a; SetDefSettings((int)a[0], (int)a[1]); return 0; }
static uint32_t m_GetMaxPeasantsInMines(const uint32_t* a){ (void)a; return (uint32_t)GetMaxPeasantsInMines(); }
static uint32_t m_UpgIsDone(const uint32_t* a){ (void)a; return (uint32_t)UpgIsDone((GAMEOBJ*)gp(a[0])); }
static uint32_t m_UpgIsRun(const uint32_t* a){ (void)a; return (uint32_t)UpgIsRun((GAMEOBJ*)gp(a[0])); }
static uint32_t m_SetMinesBuildingRules(const uint32_t* a){ (void)a; SetMinesBuildingRules((int*)gp(a[0]), (int)a[1]); return 0; }
static uint32_t m_SetMinesUpgradeRules(const uint32_t* a){ (void)a; SetMinesUpgradeRules((int*)gp(a[0])); return 0; }
static uint32_t m_FieldExist(const uint32_t* a){ (void)a; return (uint32_t)FieldExist(); }
static uint32_t m_GetDifficulty(const uint32_t* a){ (void)a; return (uint32_t)GetDifficulty(); }
static uint32_t m_GetStartRes(const uint32_t* a){ (void)a; return (uint32_t)GetStartRes(); }
static uint32_t m_GetDiff(const uint32_t* a){ (void)a; return (uint32_t)GetDiff((byte)a[0]); }
static uint32_t m_GetResOnMap(const uint32_t* a){ (void)a; return (uint32_t)GetResOnMap(); }
static uint32_t m_GetLandType(const uint32_t* a){ (void)a; return (uint32_t)GetLandType(); }
static uint32_t m_SetStandartVictory(const uint32_t* a){ (void)a; SetStandartVictory(); return 0; }
static uint32_t m_NationIsErased(const uint32_t* a){ (void)a; return (uint32_t)NationIsErased((byte)a[0]); }
static uint32_t m_AssignFormUnit(const uint32_t* a){ (void)a; AssignFormUnit((char*)gp(a[0])); return 0; }
static uint32_t m_SetPlayerName(const uint32_t* a){ (void)a; SetPlayerName((byte)a[0], (char*)gp(a[1])); return 0; }
static uint32_t m_GetMaxPeaceTime(const uint32_t* a){ (void)a; return (uint32_t)GetMaxPeaceTime(); }
static uint32_t m_GetPeaceTimeLeft(const uint32_t* a){ (void)a; return (uint32_t)GetPeaceTimeLeft(); }
static uint32_t m_GetRandomIndex(const uint32_t* a){ (void)a; return (uint32_t)GetRandomIndex(); }
static uint32_t m_SetAIRegister(const uint32_t* a){ (void)a; SetAIRegister((int)a[0], (int)a[1]); return 0; }
static uint32_t m_GetAIRegister(const uint32_t* a){ (void)a; return (uint32_t)GetAIRegister((int)a[0]); }
static uint32_t m_GetExtraction(const uint32_t* a){ (void)a; return (uint32_t)GetExtraction((byte)a[0]); }
static uint32_t m_SetDefenseState(const uint32_t* a){ (void)a; SetDefenseState((byte)a[0]); return 0; }
static uint32_t m_MissErrorMessage(const uint32_t* a){ (void)a; MissErrorMessage((char*)gp(a[0]), (char*)gp(a[1])); return 0; }
static uint32_t m_RunMapeditor(const uint32_t* a){ (void)a; RunMapeditor((char*)gp(a[0])); return 0; }
static uint32_t m_RunUserMission(const uint32_t* a){ (void)a; RunUserMission((char*)gp(a[0])); return 0; }
static uint32_t m_GetUnitExCaps(const uint32_t* a){ (void)a; return (uint32_t)GetUnitExCaps((int)a[0], (UnitExCaps*)gp(a[1]), (bool)a[2]); }
static uint32_t m_InsertUnitToGroup(const uint32_t* a){ (void)a; return (uint32_t)InsertUnitToGroup((GAMEOBJ*)gp(a[0]), (GAMEOBJ*)gp(a[1]), (int)a[2]); }
static uint32_t m_RemoveUnitFromGroup(const uint32_t* a){ (void)a; RemoveUnitFromGroup((GAMEOBJ*)gp(a[0]), (int)a[1]); return 0; }
static uint32_t m_GetZoneCoor(const uint32_t* a){ (void)a; return (uint32_t)GetZoneCoor((GAMEOBJ*)gp(a[0]), (int*)gp(a[1]), (int*)gp(a[2])); }
static uint32_t m_PastePiece(const uint32_t* a){ (void)a; PastePiece((GAMEOBJ*)gp(a[0]), (char*)gp(a[1])); return 0; }
static uint32_t m_SelectBuildingsInZone(const uint32_t* a){ (void)a; SelectBuildingsInZone((byte)a[0], (GAMEOBJ*)gp(a[1]), (GAMEOBJ*)gp(a[2]), (bool)a[3]); return 0; }

extern "C" void cos_register_gameapi(void){
  cos_api_register("AssignNation", 2, m_AssignNation);
  cos_api_register("RegisterUnits", 2, m_RegisterUnits);
  cos_api_register("RegisterUnitsForm", 2, m_RegisterUnitsForm);
  cos_api_register("RegisterString", 2, m_RegisterString);
  cos_api_register("RegisterSound", 2, m_RegisterSound);
  cos_api_register("RegisterVar", 2, m_RegisterVar);
  cos_api_register("RegisterZone", 2, m_RegisterZone);
  cos_api_register("RegisterVisibleZone", 2, m_RegisterVisibleZone);
  cos_api_register("RegisterUnitType", 2, m_RegisterUnitType);
  cos_api_register("RegisterUpgrade", 2, m_RegisterUpgrade);
  cos_api_register("SafeRegisterUpgrade", 2, m_SafeRegisterUpgrade);
  cos_api_register("InitialUpgrade", 2, m_InitialUpgrade);
  cos_api_register("DisableUpgrade", 2, m_DisableUpgrade);
  cos_api_register("EnableUpgrade", 2, m_EnableUpgrade);
  cos_api_register("EnableUnit", 3, m_EnableUnit);
  cos_api_register("RegisterFormation", 2, m_RegisterFormation);
  cos_api_register("GetUnitsAmount0", 2, m_GetUnitsAmount0);
  cos_api_register("ShowAlarm", 1, m_ShowAlarm);
  cos_api_register("SelectUnitsInZone", 3, m_SelectUnitsInZone);
  cos_api_register("ChangeUnitParam", 5, m_ChangeUnitParam);
  cos_api_register("SelectTypeOfUnitsInZone", 4, m_SelectTypeOfUnitsInZone);
  cos_api_register("GetUnitsAmount1", 2, m_GetUnitsAmount1);
  cos_api_register("GetUnitsAmount2", 3, m_GetUnitsAmount2);
  cos_api_register("GetTotalAmount0", 1, m_GetTotalAmount0);
  cos_api_register("GetTotalAmount1", 2, m_GetTotalAmount1);
  cos_api_register("GetTotalAmount2", 3, m_GetTotalAmount2);
  cos_api_register("GetReadyAmount", 2, m_GetReadyAmount);
  cos_api_register("GetAmountOfWarriors", 1, m_GetAmountOfWarriors);
  cos_api_register("IsUpgradeDoing", 2, m_IsUpgradeDoing);
  cos_api_register("IsUpgradeDone", 2, m_IsUpgradeDone);
  cos_api_register("IsUpgradeEnabled", 2, m_IsUpgradeEnabled);
  cos_api_register("GetDied", 2, m_GetDied);
  cos_api_register("CreateObject0", 6, m_CreateObject0);
  cos_api_register("ClearSelection", 1, m_ClearSelection);
  cos_api_register("SelectUnits", 2, m_SelectUnits);
  cos_api_register("SelectUnits1", 3, m_SelectUnits1);
  cos_api_register("SelectUnitsType", 3, m_SelectUnitsType);
  cos_api_register("SelDie", 1, m_SelDie);
  cos_api_register("DoMessagesBrief", 0, m_DoMessagesBrief);
  cos_api_register("SelErase", 1, m_SelErase);
  cos_api_register("SelAttackGroup", 2, m_SelAttackGroup);
  cos_api_register("SelOpenGates", 1, m_SelOpenGates);
  cos_api_register("GetNInside", 1, m_GetNInside);
  cos_api_register("GetMaxInside", 1, m_GetMaxInside);
  cos_api_register("PushUnitAway", 1, m_PushUnitAway);
  cos_api_register("PushAllUnitsAway", 1, m_PushAllUnitsAway);
  cos_api_register("SendUnitsToTransport", 1, m_SendUnitsToTransport);
  cos_api_register("CheckLeaveAbility", 1, m_CheckLeaveAbility);
  cos_api_register("AttackZoneByArtillery", 3, m_AttackZoneByArtillery);
  cos_api_register("AttackBuildingsInZone", 3, m_AttackBuildingsInZone);
  cos_api_register("ProduceOneUnit", 2, m_ProduceOneUnit);
  cos_api_register("SelCloseGates", 1, m_SelCloseGates);
  cos_api_register("SelSendTo", 4, m_SelSendTo);
  cos_api_register("SelSendAndKill", 4, m_SelSendAndKill);
  cos_api_register("Patrol", 3, m_Patrol);
  cos_api_register("ChangeFriends", 2, m_ChangeFriends);
  cos_api_register("SelChangeNation", 2, m_SelChangeNation);
  cos_api_register("SelAutoKill", 1, m_SelAutoKill);
  cos_api_register("SetStandGround", 2, m_SetStandGround);
  cos_api_register("AllowAttack", 2, m_AllowAttack);
  cos_api_register("HINT", 2, m_HINT);
  cos_api_register("DisableMission", 1, m_DisableMission);
  cos_api_register("EnableMission", 1, m_EnableMission);
  cos_api_register("SetVictoryText", 1, m_SetVictoryText);
  cos_api_register("SetLooseText", 1, m_SetLooseText);
  cos_api_register("ShowVictory", 0, m_ShowVictory);
  cos_api_register("LooseGame", 0, m_LooseGame);
  cos_api_register("ShowCentralText", 2, m_ShowCentralText);
  cos_api_register("ShowPage", 1, m_ShowPage);
  cos_api_register("ShowPageParam", 16, m_ShowPageParam);   // gather varargs off the guest stack (see m_ShowPageParam)
  cos_api_register("AskQuestion", 1, m_AskQuestion);
  cos_api_register("AskComplexQuestion", 6, m_AskComplexQuestion);
  cos_api_register("GetResource", 2, m_GetResource);
  cos_api_register("AddResource", 3, m_AddResource);
  cos_api_register("SetResource", 3, m_SetResource);
  cos_api_register("GetUnitCost", 3, m_GetUnitCost);
  cos_api_register("GetUpgradeCost", 3, m_GetUpgradeCost);
  cos_api_register("Trigg", 1, m_Trigg);
  cos_api_register("SetTrigg", 2, m_SetTrigg);
  cos_api_register("WTrigg", 1, m_WTrigg);
  cos_api_register("SetWTrigg", 2, m_SetWTrigg);
  cos_api_register("RunAI", 1, m_RunAI);
  cos_api_register("RunAIWithPeasants", 2, m_RunAIWithPeasants);
  cos_api_register("RunTimer", 2, m_RunTimer);
  cos_api_register("TimerDone", 1, m_TimerDone);
  cos_api_register("TimerDoneFirst", 1, m_TimerDoneFirst);
  cos_api_register("TimerIsEmpty", 1, m_TimerIsEmpty);
  cos_api_register("FreeTimer", 1, m_FreeTimer);
  cos_api_register("GetTime", 1, m_GetTime);
  cos_api_register("GetGlobalTime", 0, m_GetGlobalTime);
  cos_api_register("UnitsCenter", 3, m_UnitsCenter);
  cos_api_register("RefreshScreen", 0, m_RefreshScreen);
  cos_api_register("SelCenter", 3, m_SelCenter);
  cos_api_register("CreateZoneNearUnit", 5, m_CreateZoneNearUnit);
  cos_api_register("CreateZoneNearGroup", 4, m_CreateZoneNearGroup);
  cos_api_register("SetLightSpot", 3, m_SetLightSpot);
  cos_api_register("ClearLightSpot", 1, m_ClearLightSpot);
  cos_api_register("SetStartPoint", 1, m_SetStartPoint);
  cos_api_register("AttackEnemyInZone", 3, m_AttackEnemyInZone);
  cos_api_register("GetMyNation", 0, m_GetMyNation);
  cos_api_register("GetTopDst", 2, m_GetTopDst);
  cos_api_register("StartAI", 6, m_StartAI);
  cos_api_register("DoNotUseSelInAI", 1, m_DoNotUseSelInAI);
  cos_api_register("SetTutorial", 1, m_SetTutorial);
  cos_api_register("GetQuestPressed", 0, m_GetQuestPressed);
  cos_api_register("SetAIProperty", 3, m_SetAIProperty);
  cos_api_register("AskMultilineQuestion", 4, m_AskMultilineQuestion);
  cos_api_register("SetReadyState", 2, m_SetReadyState);
  cos_api_register("TakeFood", 1, m_TakeFood);
  cos_api_register("TakeWood", 1, m_TakeWood);
  cos_api_register("TakeStone", 1, m_TakeStone);
  cos_api_register("RepairBuildingsBySel", 2, m_RepairBuildingsBySel);
  cos_api_register("CheckBuildingsComplete", 1, m_CheckBuildingsComplete);
  cos_api_register("GetKilled", 1, m_GetKilled);
  cos_api_register("GetUnitsByNation", 2, m_GetUnitsByNation);
  cos_api_register("ProduceUnit", 3, m_ProduceUnit);
  cos_api_register("ProduceUnitFast", 4, m_ProduceUnitFast);
  cos_api_register("SaveSelectedUnits", 3, m_SaveSelectedUnits);
  cos_api_register("CheckProduction", 1, m_CheckProduction);
  cos_api_register("CreateBuilding", 4, m_CreateBuilding);
  cos_api_register("SetDestPoint", 2, m_SetDestPoint);
  cos_api_register("RegisterDynGroup", 1, m_RegisterDynGroup);
  cos_api_register("GetNUnits", 1, m_GetNUnits);
  cos_api_register("GetUnitInfo", 3, m_GetUnitInfo);
  cos_api_register("SetUnitInfo", 1, m_SetUnitInfo);
  cos_api_register("RemoveGroup", 2, m_RemoveGroup);
  cos_api_register("GetAINation", 0, m_GetAINation);
  cos_api_register("TryUnit", 4, m_TryUnit);
  cos_api_register("TryUpgrade", 3, m_TryUpgrade);
  cos_api_register("SetMineBalanse", 2, m_SetMineBalanse);
  cos_api_register("SetPDistribution", 3, m_SetPDistribution);
  cos_api_register("AssignAmountOfMineUpgrades", 1, m_AssignAmountOfMineUpgrades);
  cos_api_register("AssignMineUpgrade", 3, m_AssignMineUpgrade);
  cos_api_register("AssignMine", 1, m_AssignMine);
  cos_api_register("AssignPeasant", 1, m_AssignPeasant);
  cos_api_register("AssignHouse", 1, m_AssignHouse);
  cos_api_register("AssignWall", 1, m_AssignWall);
  cos_api_register("SET_MINE_CAPTURE_RADIUS", 1, m_SET_MINE_CAPTURE_RADIUS);
  cos_api_register("SET_MINE_UPGRADE1_RADIUS", 1, m_SET_MINE_UPGRADE1_RADIUS);
  cos_api_register("SET_MINE_UPGRADE2_RADIUS", 1, m_SET_MINE_UPGRADE2_RADIUS);
  cos_api_register("SET_DEFAULT_MAX_WORKERS", 1, m_SET_DEFAULT_MAX_WORKERS);
  cos_api_register("SET_MIN_PEASANT_BRIGADE", 1, m_SET_MIN_PEASANT_BRIGADE);
  cos_api_register("GetMoney", 1, m_GetMoney);
  cos_api_register("GetUnits", 1, m_GetUnits);
  cos_api_register("GetUnitsByUsage", 2, m_GetUnitsByUsage);
  cos_api_register("AI_Torg", 3, m_AI_Torg);
  cos_api_register("GetTorgResult", 3, m_GetTorgResult);
  cos_api_register("GetReadyUnits", 1, m_GetReadyUnits);
  cos_api_register("SetUpgradeLock", 2, m_SetUpgradeLock);
  cos_api_register("SetDefSettings", 2, m_SetDefSettings);
  cos_api_register("GetMaxPeasantsInMines", 0, m_GetMaxPeasantsInMines);
  cos_api_register("UpgIsDone", 1, m_UpgIsDone);
  cos_api_register("UpgIsRun", 1, m_UpgIsRun);
  cos_api_register("SetMinesBuildingRules", 2, m_SetMinesBuildingRules);
  cos_api_register("SetMinesUpgradeRules", 1, m_SetMinesUpgradeRules);
  cos_api_register("FieldExist", 0, m_FieldExist);
  cos_api_register("GetDifficulty", 0, m_GetDifficulty);
  cos_api_register("GetStartRes", 0, m_GetStartRes);
  cos_api_register("GetDiff", 1, m_GetDiff);
  cos_api_register("GetResOnMap", 0, m_GetResOnMap);
  cos_api_register("GetLandType", 0, m_GetLandType);
  cos_api_register("SetStandartVictory", 0, m_SetStandartVictory);
  cos_api_register("NationIsErased", 1, m_NationIsErased);
  cos_api_register("AssignFormUnit", 1, m_AssignFormUnit);
  cos_api_register("SetPlayerName", 2, m_SetPlayerName);
  cos_api_register("GetMaxPeaceTime", 0, m_GetMaxPeaceTime);
  cos_api_register("GetPeaceTimeLeft", 0, m_GetPeaceTimeLeft);
  cos_api_register("GetRandomIndex", 0, m_GetRandomIndex);
  cos_api_register("SetAIRegister", 2, m_SetAIRegister);
  cos_api_register("GetAIRegister", 1, m_GetAIRegister);
  cos_api_register("GetExtraction", 1, m_GetExtraction);
  cos_api_register("SetDefenseState", 1, m_SetDefenseState);
  cos_api_register("MissErrorMessage", 2, m_MissErrorMessage);
  cos_api_register("RunMapeditor", 1, m_RunMapeditor);
  cos_api_register("RunUserMission", 1, m_RunUserMission);
  cos_api_register("GetUnitExCaps", 3, m_GetUnitExCaps);
  cos_api_register("InsertUnitToGroup", 3, m_InsertUnitToGroup);
  cos_api_register("RemoveUnitFromGroup", 2, m_RemoveUnitFromGroup);
  cos_api_register("GetZoneCoor", 3, m_GetZoneCoor);
  cos_api_register("PastePiece", 2, m_PastePiece);
  cos_api_register("SelectBuildingsInZone", 4, m_SelectBuildingsInZone);
}
