/* link_gen.h — Cossacks compat shim for the SM2 decode-on-demand interpreter set
 * (decode_x86.c / ops_cache.c / interp.c). SM2's original link_gen.h was generated by
 * link_image.py and carried a module table + memory constants. Here the guest layout is
 * owned by cos_load.c / cos_modules.h, so we only provide the two constants the interpreter
 * code actually reads: the synthetic-shim threshold and the end of the DLL image region. */
#ifndef SM2_LINK_GEN_H
#define SM2_LINK_GEN_H
#include <stdint.h>

/* Addresses at/above this are synthetic import thunks (COS_SYNTH_BASE, cos_x86.h): op_at()
 * returns 0 for them so the interpreter dispatches the native shim instead of decoding. */
#define SM2_SHIM_BASE 0xE0000000u

/* Top of the guest DLL image region (all AI + mission modules load below this; current max
 * module top ~0x12ea0000). Used only for a return-address sanity range in interp diagnostics. */
#define SM2_DLL_END   0x13000000u

#endif /* SM2_LINK_GEN_H */
