/* ops.h � GENERATED by decode.py. Do not edit.
 * Compact pre-decoded x86 op table for the lean interpreter (see INTERP.md).
 * Op DATA only: classes mirror transpile.py's validated semantics 1:1. */
#ifndef LK2_X86_OPS_H
#define LK2_X86_OPS_H
#include <stdint.h>

/* operand kinds */
enum { OPK_NONE=0, OPK_REG=1, OPK_IMM=2, OPK_MEM=3, OPK_ST=4, OPK_MM=5 };

/* register slot ids (REG_* == index into interp's gpr[] for 0..7;
 * 8..11 are the high-byte regs AH/CH/DH/BH; 16..21 segment regs;
 * 255 == none). size in the Operand says 1/2/4 for the access width. */
enum { REG_EAX=0, REG_ECX=1, REG_EDX=2, REG_EBX=3, REG_ESP=4, REG_EBP=5, REG_ESI=6, REG_EDI=7, REG_AH=8, REG_CH=9, REG_DH=10, REG_BH=11, REG_ES=16, REG_CS=17, REG_SS=18, REG_DS=19, REG_FS=20, REG_GS=21, REG_NONE=255 };

/* op classes � one per distinct transpile.py semantic branch */
enum {
  OP_NOP=0,
  OP_MOV=1,
  OP_LEA=2,
  OP_MOVZX=3,
  OP_MOVSX=4,
  OP_XCHG=5,
  OP_BSWAP=6,
  OP_PUSH=7,
  OP_POP=8,
  OP_LEAVE=9,
  OP_ADD=10,
  OP_ADC=11,
  OP_SUB=12,
  OP_SBB=13,
  OP_AND=14,
  OP_OR=15,
  OP_XOR=16,
  OP_CMP=17,
  OP_TEST=18,
  OP_INC=19,
  OP_DEC=20,
  OP_NEG=21,
  OP_NOT=22,
  OP_SHL=23,
  OP_SHR=24,
  OP_SAR=25,
  OP_SHLD=26,
  OP_SHRD=27,
  OP_ROL=28,
  OP_ROR=29,
  OP_RCL=30,
  OP_RCR=31,
  OP_IMUL1=32,
  OP_IMUL=33,
  OP_MUL=34,
  OP_DIV=35,
  OP_IDIV=36,
  OP_CDQ=37,
  OP_CWDE=38,
  OP_CALL=39,
  OP_RET=40,
  OP_JMP=41,
  OP_JCC=42,
  OP_SETCC=43,
  OP_SAHF=44,
  OP_LAHF=45,
  OP_CLD=46,
  OP_STD=47,
  OP_AAS=48,
  OP_CPUID=49,
  OP_PUSHFD=50,
  OP_POPFD=51,
  OP_PUSHAD=52,
  OP_POPAD=53,
  OP_BT=54,
  OP_BTS=55,
  OP_BTR=56,
  OP_BTC=57,
  OP_JECXZ=58,
  OP_XLAT=59,
  OP_FWAIT=60,
  OP_MOVS=61,
  OP_STOS=62,
  OP_LODS=63,
  OP_SCAS=64,
  OP_CMPS=65,
  OP_FLD=66,
  OP_FILD=67,
  OP_FLDCONST=68,
  OP_FST=69,
  OP_FSTP=70,
  OP_FIST=71,
  OP_FISTP=72,
  OP_FISTTP=73,
  OP_FADD=74,
  OP_FSUB=75,
  OP_FMUL=76,
  OP_FDIV=77,
  OP_FSUBR=78,
  OP_FDIVR=79,
  OP_FIADD=80,
  OP_FISUB=81,
  OP_FIMUL=82,
  OP_FIDIV=83,
  OP_FISUBR=84,
  OP_FIDIVR=85,
  OP_FARITH_REG2=86,
  OP_FARITHP=87,
  OP_FCOM=88,
  OP_FCOMP=89,
  OP_FCOMPP=90,
  OP_FUCOM=91,
  OP_FUCOMP=92,
  OP_FUCOMPP=93,
  OP_FTST=94,
  OP_FCOMI=95,
  OP_FNSTSW=96,
  OP_FNSTCW=97,
  OP_FLDCW=98,
  OP_FCHS=99,
  OP_FABS=100,
  OP_FSQRT=101,
  OP_FRNDINT=102,
  OP_FXCH=103,
  OP_FINCSTP=104,
  OP_FDECSTP=105,
  OP_FINIT=106,
  OP_FFREE=107,
  OP_FNOP=108,
  OP_F2XM1=109,
  OP_FYL2X=110,
  OP_FYL2XP1=111,
  OP_FSCALE=112,
  OP_FPREM=113,
  OP_FPREM1=114,
  OP_FSIN=115,
  OP_FCOS=116,
  OP_FPTAN=117,
  OP_FPATAN=118,
  OP_FSINCOS=119,
  OP_FXAM=120,
  OP_FNSAVE=121,
  OP_FRSTOR=122,
  OP_FNSTENV=123,
  OP_FLDENV=124,
  OP_UNIMPL=125,
  OP_RDTSC=126,
  OP_EMMS=127,
  OP_CLC=128,
  OP_STC=129,
  OP_CMC=130,
  OP_LOOP=131,
  OP_LOOPE=132,
  OP_LOOPNE=133,
  OP_MMX=134,        /* packed MMX; Op.flags = 0F opcode byte, Op.size = shift sub-op */
  OP_NCLASS=135
};

/* condition codes for OP_JCC / OP_SETCC (Op.flags) */
enum {
  CC_O=0,
  CC_NO=1,
  CC_B=2,
  CC_AE=3,
  CC_E=4,
  CC_NE=5,
  CC_BE=6,
  CC_A=7,
  CC_S=8,
  CC_NS=9,
  CC_P=10,
  CC_NP=11,
  CC_L=12,
  CC_GE=13,
  CC_LE=14,
  CC_G=15,
  CC_N=16
};

/* Op.flags bits for string ops */
enum { STRF_REP=1, STRF_REPE=2, STRF_REPNE=4 };
/* Op.flags bit for direct (imm) call/jmp targets */
enum { TGTF_DIRECT=1 };
/* Op.flags bit: x87 op pops afterwards (fstp/fistp/fcomp/...) */
enum { FPOPF=1 };
/* x87 arithmetic sub-op (Op.flags for OP_FARITH_REG2 / OP_FARITHP):
 * bits0-2 = op(0 add,1 sub,2 mul,3 div); bit3 = reverse; bit4 = int-mem. */
enum { FA_OP=7, FA_REV=8, FA_INT=16 };
/* FLDCONST tags (Op.opnd[0].imm) */
enum { FC_1=0, FC_Z=1, FC_PI=2, FC_L2E=3, FC_L2T=4, FC_LG2=5, FC_LN2=6 };

typedef struct { uint8_t kind, reg, idx, scale, size; int32_t disp; uint32_t imm; } Operand;
/* `nxt`/`br` are lazily-filled op-chaining caches (interp.c): the decoded Op for the
 * sequential fall-through (`nxt`) and for a direct branch target (`br`), so the hot
 * loop follows pointers instead of hashing op_at() on every instruction. NULL until
 * first taken; safe because the guest image is not self-modifying after boot. */
typedef struct Op { uint32_t va; uint8_t cls, size, nopnd, flags;
                 Operand opnd[3]; uint32_t nextva;
                 struct Op *nxt, *br; } Op;   /* sequential / direct-branch next-Op caches */

extern const Op   g_ops[];
/* SM2 uses decode-on-demand (ops_cache.c): op_at() decodes+caches on first touch.
 * Returns 0 for shim-thunk / null EIP so the interpreter dispatches the shim. */
const Op *op_at(uint32_t va);

/* decode ONE guest instruction at va into *o (decode_x86.c). */
void sm2_decode(uint32_t va, Op *o);

#endif /* LK2_X86_OPS_H */
